export const ADD_PRODUCT_TO_CART_TYPE = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART_TYPE = "DELETE_PRODUCT_FROM_CART";
export const EMPTY_CART_TYPE = "EMPTY_CART";
export const INCREASE_ITEM_TYPE = "INCREASE_ITEM";
export const DECREASE_ITEM_TYPE = "DECREASE_ITEM";